# Generated by Django 2.0 on 2018-12-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
